#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

platform:
  - x64

environment:
  global:
    BINTRAY_API:
      secure: 0EYF0DvzIOWIH+sDA3zvLo2iFIeSSAn/ZhdsE7ccEXi4swwVqw1MEcyRnPeTmcJ7
    BINTRAY_USERNAME: tkralphs
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: x86_64-w64-mingw32
      HOST_ARCH_ARG: --host=x86_64-w64-mingw32 --enable-cbc-parallel
      TESTS: main
      ADD_PATH: /mingw64/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: x86_64-w64-mingw32-dbg
      HOST_ARCH_ARG: --host=x86_64-w64-mingw32 --enable-cbc-parallel --enable-debug
      TESTS: none
      ADD_PATH: /mingw64/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: i686-w64-mingw32
      HOST_ARCH_ARG: --host=i686-w64-mingw32 --enable-cbc-parallel
      TESTS: main
      ADD_PATH: /mingw32/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: i686-w64-mingw32-dbg
      HOST_ARCH_ARG: --host=i686-w64-mingw32 --enable-cbc-parallel --enable-debug
      TESTS: none
      ADD_PATH: /mingw32/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: win64-msvc14-md
      HOST_ARCH_ARG: --enable-msvc
      TESTS: main
      ADD_PATH: 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: win64-msvc15-md
      HOST_ARCH_ARG: --enable-msvc
      TESTS: main
      ADD_PATH: 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: win64-msvc16-md
      HOST_ARCH_ARG: --enable-msvc
      TESTS: main
      ADD_PATH: /mingw64/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: win64-msvc14-mdd
      HOST_ARCH_ARG: --enable-msvc --enable-debug 
      TESTS: none
      ADD_PATH: 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: win64-msvc15-mdd
      HOST_ARCH_ARG: --enable-msvc --enable-debug
      TESTS: none
      ADD_PATH: 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: win64-msvc16-mdd
      HOST_ARCH_ARG: --enable-msvc --enable-debug
      TESTS: none
      ADD_PATH: 

install:
  - for /f "delims=" %%i in ('C:\msys64\usr\bin\bash -lc "if [ $APPVEYOR_REPO_BRANCH = 'master' ]; then echo 'master'; else echo $APPVEYOR_REPO_BRANCH | cut -d "/" -f 2; fi"') do set VERSION=%%i
  - IF %ARCH%==win64-msvc14-md (CALL C:\"Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64)
  - IF %ARCH%==win64-msvc15-md (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat")
  - IF %ARCH%==win64-msvc16-md (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat")
  - IF %ARCH%==win64-msvc14-mdd (CALL C:\"Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64)
  - IF %ARCH%==win64-msvc15-mdd (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat")
  - IF %ARCH%==win64-msvc16-mdd (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat")
  - IF %ARCH%==x86_64-w64-mingw32 (CALL C:\msys64\usr\bin\bash -lc "pacman -S mingw-w64-x86_64-lapack mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-readline mingw-w64-x86_64-suitesparse mingw-w64-x86_64-metis --noconfirm")
  - IF %ARCH%==i686-w64-mingw32 (CALL C:\msys64\usr\bin\bash -lc "pacman -S mingw-w64-i686-lapack mingw-w64-i686-winpthreads-git mingw-w64-i686-readline mingw-w64-i686-suitesparse mingw-w64-i686-metis --noconfirm")  
  - C:\msys64\usr\bin\bash -lc ""

build_script:
  - C:\msys64\usr\bin\bash -lc "cd C:\projects; ln -s %APPVEYOR_PROJECT_SLUG% %APPVEYOR_PROJECT_NAME%; git clone https://github.com/coin-or/coinbrew"
  - C:\msys64\usr\bin\bash -lc "cd C:\projects; ./coinbrew/coinbrew fetch https://github.com/%APPVEYOR_REPO_NAME%@%APPVEYOR_REPO_BRANCH% --no-prompt --no-third-party --skip-update"
  - C:\msys64\usr\bin\bash -lc "cd C:\projects; export PATH=$ADD_PATH:$PATH; ./coinbrew/coinbrew build %APPVEYOR_PROJECT_NAME% --no-prompt --no-third-party --build=x86_64-w64-mingw32 $HOST_ARCH_ARG --verbosity 2 --tests $TESTS --enable-relocatable"

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

